services:
  smtp2file:
    build:
      context: .
      dockerfile: Dockerfile
    image: smtp2file
    env_file:
      - .env
    container_name: smtp2file
    ports:
      - ${HTTP_PORT:-8085}:80
      - 25:25 # Expose SMTP port
    volumes:
      - ./inbox:/app/inbox # Mount inbox directory
    # stdin_open: true
    # tty: true
    restart: unless-stopped
